export default [
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/lokesh_coder/128.jpg',
    name: 'Chandler Jacobi',
    job: 'Direct Security Executive',
    amount: 98,
    status: 'Training',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg',
    name: 'Monserrat Marquardt',
    job: 'Forward Accountability Producer',
    amount: 47,
    status: 'Passed',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jjsiii/128.jpg',
    name: 'Lonie Wyman',
    job: 'Legacy Program Director',
    amount: 93,
    status: 'Failed',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/holdenweb/128.jpg',
    name: 'Corine Abernathy',
    job: 'Chief Factors Planner',
    amount: 35,
    status: 'Failed',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/operatino/128.jpg',
    name: 'Lorenz Botsford',
    job: 'Central Accountability Developer',
    amount: 35,
    status: 'Training',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/akmur/128.jpg',
    name: 'Everette Botsford',
    job: 'Product Group Architect',
    amount: 52,
    status: 'Failed',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/nateschulte/128.jpg',
    name: 'Marilou Beahan',
    job: 'Future Security Planner',
    amount: 41,
    status: 'Training',
    date: 'Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jerrybai1907/128.jpg',
    name: 'Ceasar Sauer',
    job: 'Direct Brand Specialist',
    amount: 48,
    status: 'Passed',
    date: 'Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg',
    name: 'Rae McDermott',
    job: 'Lead Branding Engineer',
    amount: 50,
    status: 'Failed',
    date: 'Sat Feb 01 2020 12:57:03 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/rtgibbons/128.jpg',
    name: 'Mable Steuber',
    job: 'National Group Executive',
    amount: 91,
    status: 'Training',
    date: 'Mon Sep 09 2019 12:03:25 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/danthms/128.jpg',
    name: 'Julian Glover',
    job: 'Global Branding Assistant',
    amount: 65,
    status: 'Passed',
    date: 'Fri May 22 2020 17:46:12 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/andysolomon/128.jpg',
    name: 'Duncan Toy',
    job: 'Central Intranet Manager',
    amount: 12,
    status: 'Failed',
    date: 'Sun Nov 17 2019 11:59:50 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jesseddy/128.jpg',
    name: 'Blanche Friesen',
    job: 'Forward Identity Executive',
    amount: 67,
    status: 'Passed',
    date: 'Sun Jun 21 2020 16:46:39 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/haruintesettden/128.jpg',
    name: 'Orion Koepp',
    job: 'Global Accountability Strategist',
    amount: 44,
    status: 'Passed',
    date: 'Thu Jun 04 2020 18:29:41 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/vocino/128.jpg',
    name: 'Dakota Vandervort',
    job: 'Future Assurance Coordinator',
    amount: 76,
    status: 'Passed',
    date: 'Fri Jan 31 2020 13:02:55 GMT-0300 (Brasilia Standard Time)',
  },
  
  
]
